# Site Info

title: Information Security - Yuvraj Singh
tagline: 'Information Security Blog by Yuvraj Singh'
description: 'A Jekyll theme adapted from <a href="http://lanyon.getpoole.com/" target="_blank">Lanyon</a>. Made by <a href="http://codinfox.github.io" target="_blank">@codinfox</a>.'
baseurl: "/"
url: https://reg1reg1.github.io
logo: '/public/logo.png'

# Site configurations
gems:
  - jekyll-paginate
markdown: kramdown
kramdown:
  input: GFM
excerpt_separator: "<!-- more -->"
sass:
  style: compressed
  sass_dir: _scss    
paginate: 5
paginate_path: '/blog/page:num'
permalink: pretty

version: 1.0.0

# About/contact
author:
  name: Yuvraj Singh
  description: Yuvraj Singh, MS in Cybersecurity , NYU Tandon School of Engineering
  gravatar: e853a33003908c301010db762412e415 # md5 hash of your email address
  contact:
    linkedin:  https://www.linkedin.com/in/yuvraj-singh-b29228a0/
    github:    https://github.com/reg1reg1
    # facebook:  <hide>
    

# Navigation (2nd level links supported)
nav:
  Home:           
    - '/'
  Blog:           
    - '/blog/'
    - { Categories: '/blog/categories/' }
    - { Tags: '/blog/tags/' }
  About:          
    - '/about/'
  Github Project: 
    - 'https://reg1reg1.github.io/'

# Where are tags and categories displayed
tag_page: '/blog/tags/'
category_page: '/blog/categories/'

hero:
  image: /public/img/banner.jpg
  caption: Sad <i> but </i> True.

# Puglins
mathjax: true # whether support mathjax
google_analytics_token: 'UA-151890414-1' # leave blank if you don't want google analytics
disqus_short_name: 'https-reg1reg1-github-io' # leave blank if you don't want disqus


